---

- name: Ensure snapd is installed
  ansible.builtin.package:
    name: snapd
    state: present
  become: true
  become_user: root

- name: Install obsidian snap
  community.general.snap:
    name: obsidian
    state: present
    classic: true
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root
